---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  workflows:
    if: |
      github.event_name == 'release'
      || (
        github.event.workflow_run.conclusion == 'success'
        && github.event.workflow_run.event == 'push'
        && github.event.workflow_run.head_repository.full_name == github.repository
      )
    uses: ./.github/workflows/upstream-deploy.yaml
